Add methods for 2nd dragster  set book
amperka/Octoliner pull request #12
Opened 2019-07-10 16:10 UTC by yurybotov

Add methods for 2nd dragster set book (get from i2cioexpander version )

2019-07-10 16:26 UTC, nomad605dis approved these changes
LGTM

2019-07-10 16:58 UTC, nkrkv requested changes

2019-07-10 16:58 UTC, nkrkv commented on src/Octoliner.h
> +    const uint8_t _sensePin = 0;
Это константы. Их лучше вынести в global scope (в `.h` или `.cpp`), именовать `IN_UPPER_CASE` и использовать `constexpr` вместо `const`, чтобы они не потребляли RAM

2019-07-11 09:08 UTC, nkrkv approved these changes
:+1:

2019-07-11 09:11 UTC, merged