Chore prettification
amperka/Octoliner pull request #4
Opened 2019-07-03 08:55 UTC by yurybotov

Prettification and small change: comments, constant name

2019-07-03 11:29 UTC, nkrkv requested changes
The poor wording pointed below also appears on three other lines

2019-07-03 11:29 UTC, nkrkv commented on src/Octoliner.cpp
> +    Wire.write(temp); // sent to device most significant byte of value
```suggestion
    Wire.write(temp); // Send the most significant byte of `value` to the device
```

Or even simpler: “Send MSB of `value` to the device”. MSB and LSB are widely accepted abbrevs

2019-07-03 13:12 UTC, nkrkv approved these changes
LGTM :+1:

2019-07-06 05:45 UTC, nomad605dis approved these changes

2019-07-08 08:06 UTC, merged